# Solving simple differential equation with deep learning

In [1]:
# Base Data Science snippet
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import time
from tqdm import tqdm_notebook

%matplotlib inline
%load_ext autoreload
%autoreload 2

##### References
https://becominghuman.ai/neural-networks-for-solving-differential-equations-fa230ac5e04c

# Equation

$$\frac{\partial^2f }{\partial t^2}+f=0$$

## Derivatives

##### First derivative in one point

In [2]:
def d(f,x,h = 1e-5):
    return (f(x+h)-f(x-h))/2*h

##### Second derivative in one point

$$f''(x)\approx \frac{f(x+h)-2f(x)+f(x-h)}{h^2}$$

In [3]:
def d2(f,x,h = 1e-5):
    return (f(x+h)-2*f(x)+f(x-h))/h*h

##### Test of the derivatives

$$f(x)=3x^2+2x$$ $$f'(x)=6x+2$$ $$f''(x)=6$$

In [4]:
def f1(x): return 3*x**2 + 2*x

In [9]:
print(d(f1,0))
print(d(f1,1))

2.0000000000000003e-10
8.000000000008001e-10


In [10]:
print(d2(f1,0))
print(d2(f1,1))

6.000000000013156e-10
6.000009378226423e-10


# Deep Learning

## Derivatives with PyTorch

- https://discuss.pytorch.org/t/how-to-calculate-2nd-derivative-of-a-likelihood-function/15085/2
- https://discuss.pytorch.org/t/second-order-derivatives-and-inplace-gradient-zeroing/14211/3

In [40]:
import torch
from torch.autograd import Variable
from torch.autograd import grad
from torch import nn

$$f(x)=3x^2+2x$$ $$f'(x)=6x+2$$ $$f''(x)=6$$

In [33]:
def f(x): return 3*x**2 + 2*x
def f1(x): return 6*x + 2
def f2(x): return 6

### First derivative

In [36]:
def derivative(f,x):
    x = Variable(torch.FloatTensor([x]),requires_grad = True)
    y = f(x)
    y.backward()
    return x.grad

In [37]:
print(derivative(f,1))
print(f1(1))

tensor([8.])
8


In [38]:
print(derivative(f,2))
print(f1(2))

tensor([14.])
14


In [39]:
print(derivative(f,10))
print(f1(10))

tensor([62.])
62


### Second derivative

In [57]:
x = Variable(torch.FloatTensor([x]),requires_grad = True)
y = f(x)

In [60]:
y.backward(retain_graph=True)

In [61]:
x.grad

tensor([28.])

In [43]:
grads = grad(y,x,create_graph=True)

In [49]:
grad1 = grads[0]

In [ ]:
y.backward()

In [52]:
grad1.grad